on:
  push

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  image: 'library/alpine'

stages:
- stage: Build
  displayName: Build image
  jobs:
    Build:
      steps:
      - task: Docker@2
        displayName: Build an image
        inputs:
          command: build
          dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
          repository: $(image)
          tags: |
            $(tag)
      - task: CmdLine@2
        displayName: Find CVEs on image
        inputs:
          script: |
            # Install the Docker Scout CLI
            curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
            # Login to Docker Hub required for Docker Scout CLI
            docker login -u conseptraadmin -p dckr_pat_4JKwcX2ScLWr6EyP55hL-HXTk7U
            # Get a CVE report for the built image and fail the pipeline when critical or high CVEs are detected
            docker scout cves $(image):$(tag) --exit-code --only-severity critical,high